apiVersion: v1
kind: Service
metadata:
  name: rails-backend
spec:
  selector:
    app: rails
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails
          image: my-docker-hub-account/rails-app:latest
          env:
            - name: DATABASE_URL
              value: "postgres://rikusf:qweqwe@postgres:5432/mydb"
          ports:
            - containerPort: 3000
